version:  '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: design_studio_app
    env_file: .env
    volumes:
      - ./data:/code/data
    ports:
      - 8000:8000
    depends_on:
      - postgresql

  postgresql:
    image: 'postgis/postgis:16-3.4'
    ports:
      - ${OUT_POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DBNAME}
    restart: on-failure

volumes:
  postgresql:
