version:  '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: design_studio_app
    env_file: .env
    ports:
      - 8000:8000
    depends_on:
      - postgresql
    restart: on-failure

  postgresql:
    image: 'postgis/postgis:16-3.4'
    env_file: .env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
    restart: on-failure

volumes:
  postgresql:
